language: node_js
node_js:
  - node
before_script:
  - git config remote.origin.fetch "+refs/heads/*:refs/remotes/origin/*"
  - git fetch
  - git config user.name "Travis CI"
  - git config user.email "hakatasiloving@gmail.com"
  - git checkout gh-pages
  - git checkout master .
script:
  - npm run build
after_success:
  - git checkout f2b3222e3e930b33c5618b26effcf4be451841ed .gitignore
  - ls -lah
  - git status
  - git add --all
  - git commit -m "Update build"
  - git push "https://${GH_TOKEN}@github.com/tsg-ut/mnemo.git" gh-pages:gh-pages --follow-tags > /dev/null 2>&1
branches:
  except:
    - /^v\d+\.\d+\.\d+$/
    - gh-pages
notifications:
  webhooks: http://webhook.hakatashi.com/travis
